apiVersion: apps/v1
Kind: Deployment
metadata:
	name: backend-deployment
	labels:
		app:backend
spec:
  replicas:1
	selector:
    matchLabebls:
      app:backend
    template:
      metadata:
        labels:
          app:backend
      spec:
        containers:
          - name:backend
            image:benja5026/backendminikube
            imagePullPolicy:Always
            ports:
              - name: http
              containerPort:8080

