apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
   - name: http
     protocol: TCP
     port: 32000
     targetPort: 32000
     nodePort: 30000
